dataset:
  train:
    type: peprec
    structure_dir: /PepMerge
    dataset_dir: /Fixed_Data
    name: pep_pocket_train
    reset: False
    dataset_dir_mine: /Fixed_Data
    name_mine: pep_pocket_train_surf
  val:
    type: peprec
    structure_dir: /PepMerge
    dataset_dir: /Fixed_Data
    name: pep_pocket_test
    reset: False
    dataset_dir_mine: /Fixed_Data
    name_mine: pep_pocket_test_surf